import ItHero from "../../images/it-service-hero.svg";
import Itimg1 from "../../images/it-infrastructure-img1.svg";
import Itimg2 from "../../images/it-infrastructure-img2.svg";

const ServicesPageData = [
  {
    img1: ItHero,
    title: "IT INFRASTRUCTURE",
    para1:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a a marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment.",
    img2: Itimg1,
    para2:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations",
    img3: Itimg2,
    para3:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper",
  },
  {
    img1: ItHero,
    title: "DATA PROCESSING",
    para1:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a a marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment.",
    img2: Itimg1,
    para2:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations",
    img3: Itimg2,
    para3:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper",
  },
  {
    img1: ItHero,
    title: "WEB DEVELOPMENT",
    para1:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a a marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment.",
    img2: Itimg1,
    para2:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations",
    img3: Itimg2,
    para3:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper",
  },
  {
    img1: ItHero,
    title: "E-COMMERCE",
    para1:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a a marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment.",
    img2: Itimg1,
    para2:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations",
    img3: Itimg2,
    para3:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper",
  },
  {
    img1: ItHero,
    title: "CUSTOMER SUPPORT",
    para1:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a a marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment.",
    img2: Itimg1,
    para2:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations",
    img3: Itimg2,
    para3:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper",
  },
  {
    img1: ItHero,
    title: "MARKETING",
    para1:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a a marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment.",
    img2: Itimg1,
    para2:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment marketplace and assimilating the inherent strengths of different territorial locations",
    img3: Itimg2,
    para3:
      "At SwevexTECH, our mission is to drive business and bridge the divide between offshore locations by creating opportunity for profit without compromising on quality or amount of deliverables. DK Business Patron envisages the global landmass as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper on initial investment as a connected marketplace and assimilating the inherent strengths of different territorial locations, a collaborative effort towards achieving a common goal can not only make returns much more steeper",
  },
];

export default ServicesPageData;
